[package]
name = "xsa"
version = "0.0.1"
edition = "2024"
default-run = "xsa"

[dependencies]
anyhow = "1.0.104"
ash = "0.38.0"
glam = "0.33.11"
gpu-allocator = { version = "0.28.0", default-features = false, features = ["std", "vulkan"] }
image = { version = "0.25.10", default-features = false, features = ["exr"] }
winit = "0.30.13"
