//! A render graph for Vulkan 1.3 with synchronization2 and dynamic rendering.
//!
//! Passes declare the images and buffers each of their steps uses and how; the graph culls passes nothing needs,
//! derives every barrier, layout transition and attachment load and store operation, allocates the images passes
//! create and keeps history images across frames. A frame whose declarations match an earlier one reuses its
//! compiled result.

mod access;
mod attachment;
mod barrier_recorder;
mod barrier_source;
mod buffer_handle;
mod buffer_state;
mod buffer_usage;
mod buffer_usage_description;
mod compiled_attachment;
mod compiled_barrier;
mod compiled_buffer_barrier;
mod compiled_entry;
mod compiled_frame;
mod compiled_graph;
mod compiled_pass;
mod compiled_step;
mod declared_buffer;
mod declared_buffer_usage;
mod declared_image;
mod declared_image_usage;
mod declared_pass;
mod end_state;
mod frame_declaration;
mod graph_builder;
mod graph_compiler;
mod graph_description;
mod graph_image_description;
mod history_id;
mod history_image;
mod image_handle;
mod image_id;
mod image_owner;
mod image_pool;
mod image_size;
mod image_state;
mod image_usage_description;
mod imported_buffer;
mod imported_image;
mod pass_context;
mod pass_declaration;
mod pass_description;
mod pass_error;
mod pass_recording;
mod physical_image;
mod recorded_pass;
mod render_graph;
mod render_graph_error;
mod render_pass;
mod resolved_image;
mod resource_usage;
mod stage;
mod step_description;
mod subresource;

pub use attachment::Attachment;
pub use buffer_handle::BufferHandle;
pub use buffer_state::BufferState;
pub use buffer_usage::BufferUsage;
pub use buffer_usage_description::BufferUsageDescription;
pub use compiled_frame::CompiledFrame;
pub use graph_builder::GraphBuilder;
pub use graph_description::GraphDescription;
pub use graph_image_description::GraphImageDescription;
pub use history_id::HistoryId;
pub use history_image::HistoryImage;
pub use image_handle::ImageHandle;
pub use image_id::ImageId;
pub use image_size::ImageSize;
pub use image_state::ImageState;
pub use image_usage_description::ImageUsageDescription;
pub use imported_buffer::ImportedBuffer;
pub use imported_image::ImportedImage;
pub use pass_context::PassContext;
pub use pass_declaration::PassDeclaration;
pub use pass_description::PassDescription;
pub use pass_error::PassError;
pub use render_graph::RenderGraph;
pub use render_graph_error::RenderGraphError;
pub use render_pass::RenderPass;
pub use resource_usage::ResourceUsage;
pub use stage::Stage;
pub use step_description::StepDescription;
pub use subresource::Subresource;
