[package]
name = "xsa"
version.workspace = true
edition.workspace = true

[features]
default = ["client"]
client = ["server", "dep:xsa-client"]
server = ["dep:xsa-server"]

[dependencies]
anyhow.workspace = true
usage = { workspace = true, features = ["completions"] }
xsa-commands.workspace = true
xsa-client = { workspace = true, optional = true }
xsa-server = { workspace = true, optional = true }
shlex = "2.0.1"
